export let tasks = [
	{
		id: 1,
		done: true,
		taskTitle: "Milk",
		taskDescription: "buy 10 liters of milk",
		editTaskTitle: false,
		priority: false,
		date: "",
		endDate: "",
		addToMyDay: false,
	},
	{
		id: 2,
		done: true,
		taskTitle: "Butter",
		editTaskTitle: false,
		taskDescription: "Testowy opis",
		priority: true,
		date: 1619129374000,
		endDate: "",
		addToMyDay: false,
	},
	{
		id: 3,
		done: false,
		taskTitle: "Bread",
		editTaskTitle: false,
		taskDescription: "Testowy opis",
		priority: true,
		date: 1619129374000,
		endDate: "",
		addToMyDay: false,
	},
	{
		id: 4,
		done: false,
		taskTitle: "Marmelade",
		editTaskTitle: false,
		taskDescription: "Testowy opis",
		priority: false,
		date: 1619129374000,
		endDate: "",
		addToMyDay: false,
	},
	{
		id: 5,
		done: false,
		taskTitle: "Rice - brown",
		editTaskTitle: false,
		taskDescription: "",
		priority: false,
		date: 1619129374000,
		endDate: "",
		addToMyDay: false,
	},
	{
		id: 8,
		done: false,
		taskTitle: "Coffee",
		editTaskTitle: false,
		taskDescription: "Testowy opis",
		priority: true,
		date: 1619129978000,
		endDate: "",
		addToMyDay: false,
	},
];

export let emptyTaskTemplate = {
	id: "",
	done: false,
	taskTitle: "",
	editTaskTitle: false,
	taskDescription: "",
	priority: false,
	date: "",
	endDate: "",
	addToMyDay: false,
};
