export let tasks = [
	{
		id: 1,
		done: true,
		taskTitle: "Milk",
		taskDescription: "buy 10 liters of milk",
		editTaskTitle: false,
		priority: false,
		date: "",
		endDate: "",
		myDay: false,
	},
	{
		id: 2,
		done: true,
		taskTitle: "Butter",
		editTaskTitle: false,
		taskDescription: "Testowy opis",
		priority: true,
		date: 1619129374000,
		endDate: "",
		myDay: true,
	},
	{
		id: 3,
		done: false,
		taskTitle: "Bread",
		editTaskTitle: false,
		taskDescription: "Testowy opis",
		priority: true,
		date: 1619129374000,
		endDate: "",
		myDay: false,
	},
	{
		id: 4,
		done: false,
		taskTitle: "Marmelade",
		editTaskTitle: false,
		taskDescription: "Testowy opis",
		priority: false,
		date: 1619129374000,
		endDate: "",
		myDay: false,
	},
	{
		id: 5,
		done: false,
		taskTitle: "Rice - brown",
		editTaskTitle: false,
		taskDescription: "",
		priority: false,
		date: 1619129374000,
		endDate: "",
		myDay: false,
	},
	{
		id: 8,
		done: false,
		taskTitle: "Coffee",
		editTaskTitle: false,
		taskDescription: "Testowy opis",
		priority: true,
		date: 1619129978000,
		endDate: "",
		myDay: false,
	},
];

export let emptyTaskTemplate = {
	id: "",
	done: false,
	taskTitle: "",
	editTaskTitle: false,
	taskDescription: "",
	priority: false,
	date: "",
	endDate: "",
	myDay: false,
};

export let quotes = [
	{
		id: 0,
		quotation: "You only live once, but if you do it right, once is enough.",
		author: "Mae West",
	},
	{
		id: 1,
		quotation: "Many of life’s failures are people who did not realize how close they were to success when they gave up.",
		author: "Thomas A. Edison",
	},
	{
		id: 2,
		quotation: "If you want to live a happy life, tie it to a goal, not to people or things.",
		author: "Albert Einstein",
	},
	{
		id: 3,
		quotation: "Everything negative – pressure, challenges – is all an opportunity for me to rise.",
		author: "Kobe Bryant",
	},
	{
		id: 4,
		quotation: "The two most important days in your life are the day you are born and the day you find out why.",
		author: "Mark Twain",
	},
	{
		id: 5,
		quotation: "If you’re going through hell keep going.",
		author: "Winston Churchill",
	},
	{
		id: 6,
		quotation: "I find that the harder I work, the more luck I seem to have.",
		author: "Thomas Jefferson",
	},
	{
		id: 7,
		quotation: "The starting point of all achievement is desire.",
		author: "Napoleon Hill",
	},
	{
		id: 8,
		quotation: "You must expect great things of yourself before you can do them.",
		author: " Michael Jordan ",
	},
	{
		id: 9,
		quotation: "I like criticism. It makes you strong.",
		author: "LeBron James",
	},
];
